### ISSUE TITLE
Request to relocate repo to NW Utils

### ISSUE THREAD

**Issue by ayushmxn** [ayushmxn/nw-sample-apps#45]
Hi @zcbenz,

I'm a member of a GitHub organisation called NW Utils (https://github.com/nwutils/). I'm trying to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things.

Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by zcbenz** [comment]
I can transfer this project to your organization if you are interested in maintaining it.

**Comment by ayushmxn** [comment]
If you're not going to maintain it anymore I can take over. There's a lot of good examples of how to use NW.js in this repo!

**Comment by ayushmxn** [comment]
@zcbenz thanks!
